DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(30),
    last_name VARCHAR(30),
    email VARCHAR(60),
    password VARCHAR(80)
);

DROP TABLE IF EXISTS ROLES;
CREATE TABLE ROLES (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(10)
);

DROP TABLE IF EXISTS USER_ROLES;
CREATE TABLE USER_ROLES (
    user_id BIGINT,
    role_id BIGINT
);

DROP TABLE IF EXISTS ACCOUNT_TYPES;
CREATE TABLE ACCOUNT_TYPES (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    type_name VARCHAR(30)
);

DROP TABLE IF EXISTS ACCOUNTS;
CREATE TABLE ACCOUNTS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT,
    name VARCHAR(30),
    account_type_id BIGINT,
    open BOOLEAN
);

DROP TABLE IF EXISTS ACCOUNT_ENTRIES;
CREATE TABLE ACCOUNT_ENTRIES (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    account_id BIGINT,
    amount FLOAT,
    entry_date TIMESTAMP
);

DROP TABLE IF EXISTS LOAN_DETAILS;
CREATE TABLE LOAN_DETAILS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    account_id BIGINT,
    creation_date TIMESTAMP,
    original_amount FLOAT,
    monthly_payment FLOAT,
    interest_rate FLOAT,
    monthly_term INT
);

DROP TABLE IF EXISTS CREDIT_DETAILS;
CREATE TABLE CREDIT_DETAILS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    account_id BIGINT,
    credit_limit FLOAT,
    creation_date TIMESTAMP,
    cc_number VARCHAR(16),
    month_expire INT,
    year_expire INT,
    ccv INT
);